services:
  postgres:
    image: 'postgres:16.1'
    environment:
      - POSTGRES_DB=/run/secrets/db_database
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_USER=/run/secrets/db_user
    ports:
      - '5432'
    secrets:
      - db_database
      - db_password
      - db_user

  postgres_test:
    image: 'postgres:16.1'
    environment:
      - POSTGRES_DB=/run/secrets/db_database
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_USER=/run/secrets/db_user
    ports:
      - '5433:5432'
    secrets:
      - db_database
      - db_password
      - db_user

secrets:
  db_database:
    file: secrets/postgres_database.txt
  db_user:
    file: secrets/postgres_user.txt
  db_password:
    file: secrets/postgres_password.txt
